---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: east
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
