clusterGroup:
  name: west
  isHubCluster: true
  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    - hello-world
    - west
    - metallb-system:
        operatorGroup: true
        targetNamespaces: []
  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.14
    metallb:
      name: metallb-operator
      namespace: metallb-system
      channel: stable
    rhsi:
      name: skupper-operator
      namespace: openshift-operators
      channel: stable-2
    rhsi-observer:
      name: skupper-netobs-operator
      namespace: openshift-operators
      channel: stable-2
  argoProjects:
    - hub
    - hello-world
    - west
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml'
  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      argoProject: hub
      chart: acm
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      argoProject: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
    hello-world:
      name: hello-world
      namespace: hello-world
      argoProject: hello-world
      path: charts/all/hello-world
    metallb:
      name: metallb
      namespace: metallb-system
      argoProject: hub
      path: charts/all/metallb
      overrides:
      - name: metallb.myASN
        value: 65001
      - name: metallb.peerASN
        value: 64001
      - name: metallb.peerAddress
        value: 10.0.101.167
    rhsi:
      name: west
      namespace: west
      argoProject: west
      path: charts/all/rhsi
  imperative:
    jobs: []
  managedClusterGroups:
    westRegion:
      name: east
      acmlabels:
        - name: clusterGroup
          value: east
      helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
