clusterGroup:
  name: east
  isHubCluster: false
  namespaces:
    - golang-external-secrets
    - hello-world
    - east
    - metallb-system:
        operatorGroup: true
        targetNamespaces: []
  subscriptions:
    metallb:
      name: metallb-operator
      namespace: metallb-system
      channel: stable
    rhsi:
      name: skupper-operator
      namespace: openshift-operators
      channel: stable-2
    rhsi-observer:
      name: skupper-netobs-operator
      namespace: openshift-operators
      channel: stable-2
  argoProjects:
    - eso
    - hello-world
    - east
  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      argoProject: eso
      chart: golang-external-secrets
      chartVersion: 0.1.*
    hello-world:
      name: hello-world
      namespace: hello-world
      argoProject: hello-world
      path: charts/all/hello-world
    metallb:
      name: metallb
      namespace: metallb-system
      argoProject: east
      path: charts/all/metallb
      overrides:
      - name: metallb.myASN
        value: 65002
      - name: metallb.peerASN
        value: 64002
      - name: metallb.peerAddress
        value: 10.1.127.254
    rhsi:
      name: east
      namespace: east
      argoProject: east
      path: charts/east-site/rhsi-east
  imperative:
    jobs: []
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
    - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml'
