- name: Output configs
  ansible.builtin.debug:
    msg: "WESTCONFIG: {{ WESTCONFIG }} - EASTCONFIG: {{ EASTCONFIG }}"

- name: Fetch regional cluster info
  ansible.builtin.include_tasks:
    file: region-fetch-api.yml
    apply:
      environment:
        KUBECONFIG: "{{ EASTCONFIG }}"

- name: Add the regional cluster to the ACM hub
  ansible.builtin.include_tasks:
    file: hub-acm-add-regional-cluster.yml
