- name: Fetch API endpoint of regional cluster
  kubernetes.core.k8s_cluster_info:
  register: acm_import_cluster_info

- name: Set regional api fact
  ansible.builtin.set_fact:
    acm_import_region_api: "{{ acm_import_cluster_info['connection']['host'] }}"

# FIXME(bandini): This currently seems the sanest way to be sure of the cluster name being used as k8s has no concept
# of own cluster name and other hacks like parsing the API url seem worse than this
- name: Find regional cluster name
  ansible.builtin.shell: |
    {% raw %}
    oc config view --raw -o go-template="{{ range .clusters }}{{ if and
    (eq .cluster.server \"${API}\")
    (index .cluster \"certificate-authority-data\") }}{{ .name }}{{ end }}{{ end }}"
    {% endraw %}
  register: acm_import_region_cluster_oc
  changed_when: false
  environment:
    API: "{{ acm_import_region_api }}"

- name: Set regional cluster name fact
  ansible.builtin.set_fact:
    acm_import_region_cluster_name: "{{ acm_import_region_cluster_oc.stdout }}"
  failed_when: acm_import_region_cluster_oc.stdout | length == 0

# This is strictly not needed but could be useful eventually
- name: Find regional CA
  ansible.builtin.shell: |
    {% raw %}
    oc config view --raw -o go-template="{{ range .clusters }}{{ if and
    (eq .cluster.server \"${API}\")
    (index .cluster \"certificate-authority-data\") }}{{ index .cluster \"certificate-authority-data\" }}{{ end }}{{ end }}"
    {% endraw %}
  register: acm_import_region_cluster_ca
  changed_when: false
  environment:
    API: "{{ acm_import_region_api }}"

- name: Set regional CA fact
  ansible.builtin.set_fact:
    acm_import_region_ca: "{{ acm_import_region_cluster_ca.stdout }}"
  failed_when: acm_import_region_cluster_ca.stdout | length == 0
